openapi: '3.0.2'
info:
  title: API Documentation
  version: '1.0'
servers:
  - url: https://localhost:3000/api
paths:
  /users/login:
    post:
      responses:
        '200':
          description: OK
